version: "3.4"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/src
            - ./local.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: .
        command: ["./start-php-fpm.sh"]
        depends_on:
            - postgres
            - redis
        volumes:
            - ./app:/src/app
            - ./config:/src/config
            - ./database:/src/database
            - ./resources:/src/resources
            - ./routes:/src/routes
            - ./storage:/src/storage
            - ./tests:/src/tests
            - ./composer.json:/src/composer.json
            - ./composer.lock:/src/composer.lock
            - ./.env:/src/.env
            - ./.env.example:/src/.env.example
            - ./start-php-fpm.sh:/src/start-php-fpm.sh
            - ./phpunit.xml:/src/phpunit.xml
            - ./ruleset.xml:/src/ruleset.xml
        environment:
            COMPOSER_MEMORY_LIMIT: 4G
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=homestead
            - POSTGRES_USER=homestead
            - POSTGRES_PASSWORD=secret
        ports:
            - "54345:5432"
        volumes:
            - db:/var/lib/postgresql/data
    redis:
        image: redis:latest

volumes:
    db:
